# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Professional page from krlsdu
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://krlsdu.github.io" # the base hostname & protocol for your site
twitter_username: krlsdu
github_username:  krlsdu

# Build settings
markdown: kramdown
plugins:
 - jekyll-sitemap
 - jekyll-redirect-from
exclude: [vendor, Gemfile, Guardfile, README, bower]

webrick:
  headers:
    Content-Security-Policy: " default-src 'self'; img-src 'self'; style-src 'self' 'unsafe-inline' "
    Strict-Transport-Security: max-age=86400; includeSubDomains
